version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mouts_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mouts_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: mouts_backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm install -g @nestjs/cli && npm run build && npm run start:prod"

  frontend:
    build: ./frontend
    container_name: mouts_frontend
    restart: always
    depends_on:
      - backend
    environment:
      API_URL: ${API_URL}
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  redis_data: