version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mouts_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mouts_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: mouts_backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    command: npm run start:prod

  frontend:
    build: ./frontend
    container_name: mouts_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: npm run start

volumes:
  postgres_data:
  redis_data: